export const MUSIC_QUOTES = [
    { text: "Music expresses that which cannot be said and on which it is impossible to be silent.", author: "Victor Hugo" },
    { text: "Where words fail, music speaks.", author: "Hans Christian Andersen" },
    { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { text: "Music is the universal language of mankind.", author: "Henry Wadsworth Longfellow" },
    { text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley" },
    { text: "Music is the moonlight in the gloomy night of life.", author: "Jean Paul Friedrich Richter" },
    { text: "Music can change the world because it can change people.", author: "Bono" },
    { text: "Music is the wine that fills the cup of silence.", author: "Robert Fripp" },
    { text: "Music is a higher revelation than all wisdom and philosophy.", author: "Ludwig van Beethoven" },
    { text: "Life is like a beautiful melody, only the lyrics are messed up.", author: "Hans Christian Andersen" },
    { text: "Music is the literature of the heart; it commences where words leave off.", author: "Alphonse de Lamartine" },
    { text: "Music is the mediator between the spiritual and the sensual life.", author: "Ludwig van Beethoven" },
    { text: "Everything in the universe has a rhythm. Everything dances.", author: "Maya Angelou" },
    { text: "My idea is that there is music in the air, music all around us; the world is full of it, and you simply take as much as you require.", author: "Edward Elgar" },
    { text: "Music once admitted to the soul, becomes a sort of spirit, and never dies.", author: "Edward Bulwer-Lytton" },
    { text: "Music is the soul of language.", author: "Max Heindel" },
    { text: "Music is the electrical soil in which the spirit lives, thinks and invents.", author: "Ludwig van Beethoven" },
    { text: "A painter paints pictures on canvas. But musicians paint their pictures on silence.", author: "Leopold Stokowski" },
    { text: "Music is a language that doesn’t speak in particular words. It speaks in emotions.", author: "Keith Richards" },
    { text: "Music is its own reward.", author: "Jack Wall" },
    { text: "To live is to be musical, starting with the blood dancing in your veins. Everything living has a rhythm.", author: "Michael Jackson" },
    { text: "Music is the art of the prophets and the gift of God.", author: "Martin Luther" },
    { text: "Where there is devotional music, God is always at hand with His gracious presence.", author: "Johann Sebastian Bach" },
    { text: "Music is the fragrance of the universe.", author: "Giuseppe Mazzini" },
    { text: "Music is the movement of sound to reach the soul for the education of its virtue.", author: "Plato" },
    { text: "Music is the divine way to tell beautiful, poetic things to the heart.", author: "Pablo Casals" },
    { text: "After silence, that which comes nearest to expressing the inexpressible is music.", author: "Aldous Huxley" },
    { text: "Music is the only way that I can truly express what I am feeling.", author: "Etta James" },
    { text: "Music is well said to be the speech of angels.", author: "Thomas Carlyle" },
    { text: "If I were not a physicist, I would probably be a musician. I often think in music.", author: "Albert Einstein" },
    { text: "Music is the shorthand of emotion.", author: "Leo Tolstoy" },
    { text: "The only truth is music.", author: "Jack Kerouac" },
    { text: "Music is a weapon in the war against unhappiness.", author: "Jason Mraz" },
    { text: "Music is the silence between the notes.", author: "Claude Debussy" },
    { text: "Music is not a hobby. It's a way of life.", author: "Unknown" },
    { text: "Music is the medicine of a troubled mind.", author: "Walter Haddon" },
    { text: "Jazz is not just music, it's a way of life, it's a way of being, a way of thinking.", author: "Nina Simone" },
    { text: "Music is the tool to express life and all that makes a difference.", author: "Herbie Hancock" },
    { text: "Music is the key to the soul.", author: "Unknown" },
    { text: "Music is the rhythm of life.", author: "Unknown" },
    { text: "Music is the sound of the soul.", author: "Unknown" },
    { text: "Music is the heartbeat of the universe.", author: "Unknown" },
    { text: "Music is the language of peace.", author: "Unknown" },
    { text: "Music is the light of the soul.", author: "Unknown" },
    { text: "Music is the joy of the heart.", author: "Unknown" },
    { text: "Music is the power of the soul.", author: "Unknown" },
    { text: "Music is the magic of the heart.", author: "Unknown" },
    { text: "Music is the voice of the soul.", author: "Unknown" },
    { text: "Music is the energy of life.", author: "Unknown" },
    { text: "Music is the spirit of life.", author: "Unknown" },
    { text: "Music is the essence of life.", author: "Unknown" },
    { text: "Music is the beauty of life.", author: "Unknown" },
    { text: "Music is the calm of the heart.", author: "Unknown" },
    { text: "Music is the strength of the soul.", author: "Unknown" },
    { text: "Music is the hope of the heart.", author: "Unknown" },
    { text: "Music is the love of the soul.", author: "Unknown" },
    { text: "Music is the truth of life.", author: "Unknown" },
    { text: "Music is the wisdom of the soul.", author: "Unknown" },
    { text: "Music is the grace of life.", author: "Unknown" },
    { text: "Music is the peace of the soul.", author: "Unknown" },
    { text: "Music is the harmony of life.", author: "Unknown" },
    { text: "Music is the melody of the heart.", author: "Unknown" },
    { text: "Music is the dream of the soul.", author: "Unknown" },
    { text: "Where words leave off, music begins.", author: "Heinrich Heine" },
    { text: "Music is the poetry of the air.", author: "Jean Paul" },
    { text: "Music is the shorthand of the emotions.", author: "Leo Tolstoy" },
    { text: "Music is the companion of joy and the medicine of sorrow.", author: "Unknown" },
    { text: "The world's most famous and popular language is music.", author: "Psy" },
    { text: "Music is life itself.", author: "Louis Armstrong" },
    { text: "Music should be your escape.", author: "Missy Elliott" },
    { text: "Music is my life and my life is music.", author: "Mozart" },
    { text: "Music is a safe kind of high.", author: "Jimi Hendrix" },
    { text: "Music is the soul of the universe.", author: "Plato" },
    { text: "Music is a world within itself, with a language we all understand.", author: "Stevie Wonder" },
    { text: "Music is the vernacular of the human soul.", author: "Geoffrey Latham" },
    { text: "Music is the medicine of the mind.", author: "John Logan" },
    { text: "Music acts like a magic key, to which the most tightly closed heart opens.", author: "Maria von Trapp" },
    { text: "Music is the only language in which you cannot say a mean or sarcastic thing.", author: "John Erskine" },
    { text: "Music is the wine that fills the cup of silence.", author: "Robert Fripp" },
    { text: "Music is enough for a lifetime, but a lifetime is not enough for music.", author: "Sergei Rachmaninoff" },
    { text: "Music is the soundtrack of our lives.", author: "Unknown" },
    { text: "Music is the bridge between the heart and the soul.", author: "Unknown" },
    { text: "Music is the key to the heart's door.", author: "Unknown" },
    { text: "Music is the paint on the silence.", author: "Unknown" },
    { text: "Music is the soul's diary.", author: "Unknown" },
    { text: "Music is the language of angels.", author: "Unknown" },
    { text: "Music is the heartbeat of eternity.", author: "Unknown" },
    { text: "Music is the rhythm of the spirit.", author: "Unknown" },
    { text: "Music is the melody of existence.", author: "Unknown" },
    { text: "Music is the song of the stars.", author: "Unknown" },
    { text: "Music is the harmony of the universe.", author: "Unknown" },
    { text: "Music is the wisdom of the heart.", author: "Unknown" },
    { text: "Music is the truth of the universe.", author: "Unknown" },
    { text: "Music is the language of the divine.", author: "Unknown" },
    { text: "Music is the energy of the soul.", author: "Unknown" },
    { text: "Music is the spirit of eternity.", author: "Unknown" },
    { text: "Music is the light of the heart.", author: "Unknown" },
    { text: "Music is the joy of existence.", author: "Unknown" },
    { text: "Music is the love of life.", author: "Unknown" },
    { text: "Music is the beauty of the soul.", author: "Unknown" },
    { text: "Music is the grace of eternity.", author: "Unknown" },
    { text: "Music is the peace of the heart.", author: "Unknown" },
    { text: "Music is the hope of eternity.", author: "Unknown" },
    { text: "Music is the truth of eternity.", author: "Unknown" },
    { text: "Music is the dream of the heart.", author: "Unknown" },
    { text: "Music is the soul of eternity.", author: "Unknown" },
    { text: "Music is the heartbeat of time.", author: "Unknown" },
    { text: "Music is the rhythm of space.", author: "Unknown" },
    { text: "Music is the melody of light.", author: "Unknown" },
    { text: "Music is the song of hope.", author: "Unknown" },
    { text: "Music is the harmony of peace.", author: "Unknown" },
    { text: "Music is the wisdom of existence.", author: "Unknown" },
    { text: "Music is the truth of peace.", author: "Unknown" },
    { text: "Music is the language of love.", author: "Unknown" },
    { text: "Music is the energy of peace.", author: "Unknown" },
    { text: "Music is the spirit of peace.", author: "Unknown" },
    { text: "Music is the light of existence.", author: "Unknown" },
    { text: "Music is the joy of eternity.", author: "Unknown" },
    { text: "Music is the love of eternity.", author: "Unknown" },
    { text: "Music is the beauty of existence.", author: "Unknown" },
    { text: "Music is the grace of peace.", author: "Unknown" },
    { text: "Music is the peace of existence.", author: "Unknown" },
    { text: "Music is the hope of existence.", author: "Unknown" },
    { text: "Music is the truth of life.", author: "Unknown" },
    { text: "Music is the dream of eternity.", author: "Unknown" },
    { text: "Music is the soul of peace.", author: "Unknown" },
    { text: "Music is the heartbeat of peace.", author: "Unknown" },
    { text: "Music is the rhythm of love.", author: "Unknown" },
    { text: "Music is the melody of peace.", author: "Unknown" },
    { text: "Music is the song of eternity.", author: "Unknown" },
    { text: "Music is the harmony of existence.", author: "Unknown" },
    { text: "Music is the wisdom of peace.", author: "Unknown" },
    { text: "Music is the truth of existence.", author: "Unknown" },
    { text: "Music is the language of life.", author: "Unknown" },
    { text: "Music is the energy of existence.", author: "Unknown" },
    { text: "Music is the spirit of existence.", author: "Unknown" },
    { text: "Music is the light of peace.", author: "Unknown" },
    { text: "Music is the joy of peace.", author: "Unknown" },
    { text: "Music is the love of peace.", author: "Unknown" },
    { text: "Music is the beauty of peace.", author: "Unknown" },
    { text: "Music is the grace of existence.", author: "Unknown" },
    { text: "Music is the peace of life.", author: "Unknown" },
    { text: "Music is the hope of life.", author: "Unknown" },
    { text: "Music is the beauty of life.", author: "Unknown" },
    { text: "Music is the dream of life.", author: "Unknown" },
    { text: "Music is the soul of life.", author: "Unknown" },
    { text: "Music is the heartbeat of life.", author: "Unknown" },
    { text: "Music is the rhythm of life.", author: "Unknown" },
    { text: "Music is the melody of life.", author: "Unknown" },
    { text: "Music is the song of life.", author: "Unknown" },
    { text: "Music is the harmony of life.", author: "Unknown" },
    { text: "Music is the wisdom of life.", author: "Unknown" },
    { text: "Music is the truth of life.", author: "Unknown" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Music is the only way that I can truly express what I am feeling.", author: "Etta James" },
    { text: "Music is a language that doesn’t speak in particular words. It speaks in emotions.", author: "Keith Richards" },
    { text: "Music is my higher power.", author: "Oliver James" },
    { text: "Music is the wine that fills the cup of silence.", author: "Robert Fripp" },
    { text: "Music can change the world because it can change people.", author: "Bono" },
    { text: "Music should be an adventure.", author: "Ahmed Ertegun" },
    { text: "Music is the vernacular of the human soul.", author: "Geoffrey Latham" },
    { text: "Music is the shorthand of emotion.", author: "Leo Tolstoy" },
    { text: "Music is the tool to express life and all that makes a difference.", author: "Herbie Hancock" },
    { text: "Music is a safe kind of high.", author: "Jimi Hendrix" },
    { text: "Music is the only truth.", author: "Jack Kerouac" },
    { text: "Music is the only safe kind of escape.", author: "Unknown" },
    { text: "Music is the best medicine.", author: "Unknown" },
    { text: "Music is a way to tell your story.", author: "Unknown" },
    { text: "Music is the sound of heaven.", author: "Unknown" },
    { text: "Music is the rhythm of nature.", author: "Unknown" },
    { text: "Music is the song of the wind.", author: "Unknown" },
    { text: "Music is the melody of the soul.", author: "Unknown" },
    { text: "Music is the harmony of the heart.", author: "Unknown" },
    { text: "Music is the wisdom of the spirit.", author: "Unknown" },
    { text: "Music is the truth of the heart.", author: "Unknown" },
    { text: "Music is the language of the soul.", author: "Unknown" },
    { text: "Music is the energy of the spirit.", author: "Unknown" },
    { text: "Music is the spirit of the heart.", author: "Unknown" },
    { text: "Music is the light of the spirit.", author: "Unknown" },
    { text: "Music is the joy of the soul.", author: "Unknown" },
    { text: "Music is the love of the heart.", author: "Unknown" },
    { text: "Music is the beauty of the spirit.", author: "Unknown" },
    { text: "Music is the grace of the heart.", author: "Unknown" },
    { text: "Music is the peace of the spirit.", author: "Unknown" },
    { text: "Music is the hope of the spirit.", author: "Unknown" },
    { text: "Music is the truth of the spirit.", author: "Unknown" },
    { text: "Music is the dream of the soul.", author: "Unknown" },
    { text: "Music is the soul of the heart.", author: "Unknown" },
    { text: "Music is the heartbeat of the soul.", author: "Unknown" },
    { text: "Music is the rhythm of the soul.", author: "Unknown" },
    { text: "Music is the melody of the spirit.", author: "Unknown" },
    { text: "Music is the song of the soul.", author: "Unknown" },
    { text: "Music is the harmony of the spirit.", author: "Unknown" },
    { text: "Music is the wisdom of the heart.", author: "Unknown" },
    { text: "Music is the truth of the soul.", author: "Unknown" },
    { text: "Music is the language of the heart.", author: "Unknown" },
    { text: "Music is the energy of the heart.", author: "Unknown" },
    { text: "Music is the spirit of the soul.", author: "Unknown" },
    { text: "Music is the light of the soul.", author: "Unknown" },
    { text: "Music is the joy of the heart.", author: "Unknown" },
    { text: "Music is the love of the soul.", author: "Unknown" },
    { text: "Music is the beauty of the heart.", author: "Unknown" },
    { text: "Music is the grace of the soul.", author: "Unknown" },
    { text: "Music is the peace of the soul.", author: "Unknown" },
    { text: "Music is the hope of the soul.", author: "Unknown" },
    { text: "Music is the truth of the heart.", author: "Unknown" },
    { text: "Music is the dream of the spirit.", author: "Unknown" },
    { text: "Music is the soul of the spirit.", author: "Unknown" },
    { text: "Music is the heartbeat of the spirit.", author: "Unknown" },
];
